-- Tabla Color:
INSERT INTO `car_api`.`color` (`name`) VALUES
('Alpine White'),
('Beige'),
('Black'),
('Black Sapphire Metallic'),
('Brown'),
('Burgundy'),
('Carbon Black Metallic'),
('Champagne'),
('Charcoal'),
('Cognac'),
('Copper'),
('Coral Red Black'),
('Cream'),
('Dark Blue'),
('Dark Graphite Metallic'),
('Dark Green'),
('Dark Grey'),
('Dark Red'),
('Glacier Silver Metallic'),
('Gold'),
('Gray'),
('Ivory'),
('Ivory White Black'),
('Jet Black'),
('Light Blue'),
('Light Brown'),
('Light Green'),
('Light Grey'),
('Light Gan'),
('Lime'),
('Magma Red'),
('Medium Blue'),
('Medium Brown'),
('Medium Green'),
('Medium Grey'),
('Melbourne Red Metallic'),
('Mineral Gray Metallic'),
('Mineral White Metallic'),
('Moonstone Metallic'),
('Night Blue'),
('Olive'),
('Oyster Black'),
('Pink'),
('platinum Gray Metallic'),
('Purple'),
('Pyrite Brown Metallic'),
('Saddle Brown'),
('Silver'),
('Sophisto Gray Metallic'),
('Sparkling Brown Metallic'),
('Sunset Orange Metallic'),
('Tan'),
('Tanzanite Blue Metallic'),
('Terra'),
('Turquoise'),
('Valencia Orange Metallic'),
('White');


-- Tabla Schedule:
INSERT INTO `car_api`.`schedule` (`hour`) VALUES
('8:00'),
('8:30'),
('9:00'),
('9:30'),
('10:00'),
('10:30'),
('11:00'),
('11:30'),
('12:00'),
('12:30'),
('13:00'),
('13:30'),
('14:00'),
('14:30'),
('15:00'),
('15:30'),
('16:00'),
('16:30'),
('17:00');


-- Tabla Maker:
INSERT INTO `car_api`.`maker` (`name`, `logo`, `createdAt`, `updatedAt`) VALUES
('Acura', 'https://www.carlogos.org/logo/Acura-logo-2001-2048x2048.png', NOW(), NOW()),
('Alfa-Romeo', 'https://www.carlogos.org/logo/Alfa-Romeo-logo-1920x1080.png', NOW(), NOW()),
('Aston-Martin', 'https://www.carlogos.org/logo/Aston-Martin-logo-2003-2560x1440.png', NOW(), NOW()),
('Audi', 'https://www.carlogos.org/logo/Audi-logo-2009-1920x1080.png', NOW(), NOW()),
('Bentley', 'https://www.carlogos.org/logo/Bentley-logo-2003-2048x2048.png', NOW(), NOW()),
('BMW', 'https://www.carlogos.org/logo/BMW-logo-1920x1080.png', NOW(), NOW()),
('Bugatti', 'https://www.carlogos.org/logo/Bugatti-logo-2019-2048x2048.png', NOW(), NOW()),
('Buick', 'https://www.carlogos.org/logo/Buick-logo-2019-2560x1440.png', NOW(), NOW()),
('Cadillac', 'https://www.carlogos.org/logo/Cadillac-logo-2014-2048x2048.png', NOW(), NOW()),
('Chevrolet', 'https://www.carlogos.org/logo/Chevrolet-logo-2013-2048x2048.png', NOW(), NOW()),
('Chrysler', 'https://www.carlogos.org/logo/Chrysler-logo-2010-1920x1080.png', NOW(), NOW()),
('Dodge', 'https://www.carlogos.org/logo/Dodge-logo-2010-2560x1440.png', NOW(), NOW()),
('Ferrari', 'https://www.carlogos.org/logo/Ferrari-logo-2002-2048x2048.png', NOW(), NOW()),
('Fiat', 'https://www.carlogos.org/logo/Fiat-logo-2006-2048x2048.png', NOW(), NOW()),
('Ford', 'https://www.carlogos.org/logo/Ford-logo-2003-1920x1080.png', NOW(), NOW()),
('Genesis', 'https://www.carlogos.org/logo/Genesis-logo-2015-2048x2048.png', NOW(), NOW()),
('GMC', 'https://www.carlogos.org/logo/GMC-logo-2010-2048x2048.png', NOW(), NOW()),
('Honda', 'https://www.carlogos.org/logo/Honda-logo-2013-2048x2048.png', NOW(), NOW()),
('Hyundai', 'https://i.imgur.com/54KgzMa.png', NOW(), NOW()),
('Infiniti', 'https://i.imgur.com/vzT2QwT.png', NOW(), NOW()),
('Jaguar', 'https://www.carlogos.org/logo/Jaguar-logo-2012-2560x1440.png', NOW(), NOW()),
('Jeep', 'https://www.carlogos.org/logo/Jeep-logo-2011-2048x2048.png', NOW(), NOW()),
('Lexus', 'https://i.imgur.com/TL6lTPx.png', NOW(), NOW()),
('Lincoln', 'https://www.carlogos.org/logo/Lincoln-logo-2012-2048x2048.png', NOW(), NOW()),
('Lotus', 'https://www.carlogos.org/logo/Lotus-logo-2560x1440.png', NOW(), NOW()),
('Maserati', 'https://www.carlogos.org/logo/Maserati-logo-2018-2048x2048.png', NOW(), NOW()),
('Mazda', 'https://www.carlogos.org/logo/Mazda-logo-2015-2560x1440.png', NOW(), NOW()),
('McLaren', 'https://www.carlogos.org/logo/McLaren-logo-2019-2560x1440.png', NOW(), NOW()),
('Mercedes-Benz', 'https://www.carlogos.org/logo/Mercedes-Benz-logo-2011-2560x1440.png', NOW(), NOW()),
('Mini', 'https://www.carlogos.org/logo/Mini-logo-2001-1920x1080.png', NOW(), NOW()),
('Mitsubishi', 'https://www.carlogos.org/logo/Mitsubishi-logo-2017-2048x2048.png', NOW(), NOW()),
('Nissan', 'https://www.carlogos.org/logo/Nissan-logo-2013-2560x1440.png', NOW(), NOW()),
('Opel', 'https://www.carlogos.org/logo/Opel-logo-2019-2560x1440.png', NOW(), NOW()),
('Pagani', 'https://www.carlogos.org/logo/Pagani-logo-2560x1440.png', NOW(), NOW()),
('Peugeot', 'https://www.carlogos.org/logo/Peugeot-logo-2019-2048x2048.png', NOW(), NOW()),
('Porsche', 'https://www.carlogos.org/logo/Porsche-logo-2003-2560x1440.png', NOW(), NOW()),
('RAM', 'https://www.carlogos.org/logo/Ram-logo-2015-2560x1440.png', NOW(), NOW()),
('Renault', 'https://www.carlogos.org/logo/Renault-logo-2015-2048x2048.png', NOW(), NOW()),
('Rolls-Royce', 'https://www.carlogos.org/logo/Rolls-Royce-logo-2018-2048x2048.png', NOW(), NOW()),
('Seat', 'https://www.carlogos.org/logo/Seat-logo-2012-2560x1440.png', NOW(), NOW()),
('Smart', 'https://www.carlogos.org/logo/Smart-logo-2018-2560x1440.png', NOW(), NOW()),
('Subaru', 'https://www.carlogos.org/logo/Subaru-logo-2017-2560x1440.png', NOW(), NOW()),
('Suzuki', 'https://www.carlogos.org/logo/Suzuki-logo-2019-2560x1440.png', NOW(), NOW()),
('Tesla', 'https://www.carlogos.org/logo/Tesla-logo-2018-2048x2048.png', NOW(), NOW()),
('Toyota', 'https://www.carlogos.org/logo/Toyota-logo-', NOW(), NOW());


-- Tabla transmission:
INSERT INTO `car_api`.`transmission` (`type`, `createdAt`, `updatedAt`) VALUES
('Manual', NOW(), NOW()),
('Automatic', NOW(), NOW());


-- Tabla state:
INSERT INTO `car_api`.`state` (`name`, `createdAt`, `updatedAt`) VALUES
('Aguascalientes', NOW(), NOW()),
('Baja California', NOW(), NOW()),
('Baja California Sur', NOW(), NOW()),
('Campeche', NOW(), NOW()),
('CdMx', NOW(), NOW()),
('Chiapas', NOW(), NOW()),
('Chihuahua', NOW(), NOW()),
('Coahuila', NOW(), NOW()),
('Colima', NOW(), NOW()),
('Durango', NOW(), NOW()),
('Estado de México', NOW(), NOW()),
('Guanajuato', NOW(), NOW()),
('Guerrero', NOW(), NOW()),
('Hidalgo', NOW(), NOW()),
('Jalisco', NOW(), NOW()),
('Michoacán', NOW(), NOW()),
('Morelos', NOW(), NOW()),
('Nayarit', NOW(), NOW()),
('Nuevo León', NOW(), NOW()),
('Oaxaca', NOW(), NOW()),
('Puebla', NOW(), NOW()),
('Querétaro', NOW(), NOW()),
('Quintana Roo', NOW(), NOW()),
('San Luis Potosí', NOW(), NOW()),
('Sinaloa', NOW(), NOW()),
('Sonora', NOW(), NOW()),
('Tabasco', NOW(), NOW()),
('Tamaulipas', NOW(), NOW()),
('Tlaxcala', NOW(), NOW()),
('Veracruz', NOW(), NOW()),
('Yucatán', NOW(), NOW()),
('Zacatecas', NOW(), NOW());


-- Tabla postal_code
INSERT INTO `car_api`.`postal_code` (`code`, `state`, `createdAt`, `updatedAt`) VALUES
("20000", 1, NOW(), NOW()),
("21000", 2, NOW(), NOW()),
("23000", 3, NOW(), NOW()),
("24000", 4, NOW(), NOW()),
("01000 ", 5, NOW(), NOW());


-- Tabla car_category:
INSERT INTO `car_api`.`car_category` (`name`, `createdAt`, `updatedAt`) VALUES
("Convertible",NOW(),NOW()),
("Coupe",NOW(),NOW()),
("Hatchback",NOW(),NOW()),
("Minivan",NOW(),NOW()),
("Pickup",NOW(),NOW()),
("Sedan",NOW(),NOW()),
("SUV",NOW(),NOW()),
("Van",NOW(),NOW()),
("Wagon",NOW(),NOW());


-- Tabla dealserhip:
INSERT INTO `car_api`.`dealership` (`name`, `description`, `street`, `exterior_number`, `neighborhood`, `postal_code`, `createdAt`, `updatedAt`) VALUES
( 'Donut-Motors Cars Emporium', "", "Calle Morelos", "123", "Centro", 1, NOW(), NOW()),
( 'Donut-Motors Vintage Auto Gallery', "", "Calle Juárez", "456", "Zona Centro", 2, NOW(), NOW()),
( 'Donut-Motors Automobile Dealership', "", "Calle Hidalgo", "789", "San José Viejo", 3, NOW(), NOW()),
( 'Donut-Motors Retro Ride Showroom', "", "Calle Reforma", "101", "San Francisco", 4, NOW(), NOW()),
( 'Donut-Motors Timeless Car Boutique', "", "Calle Insurgentes", "112", "Roma Norte", 5, NOW(), NOW());